services:
  - type: web
    name: mits-ims
    env: python
    buildCommand: pip install -r requirements.txt && python -m playwright install chromium
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
